# Generated by Django 3.1.6 on 2021-02-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
