# Generated by Django 3.1.6 on 2021-02-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_place_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='googleAddres',
            new_name='googleAddress',
        ),
    ]
