# Generated by Django 3.1.6 on 2021-02-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210204_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
